# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

default:
    suites:
        api_shopping_cart:
            contexts:
                - sylius.behat.context.hook.doctrine_orm

                - sylius.behat.context.setup.channel
                - sylius.behat.context.setup.product
                - sylius.behat.context.setup.shipping
                - sylius.behat.context.setup.shop_api_security
                - sylius.behat.context.setup.zone
#                - sylius.behat.context.setup.currency
#                - sylius.behat.context.setup.exchange_rate
#                - sylius.behat.context.setup.shipping_category
#                - sylius.behat.context.setup.taxation
#                - sylius.behat.context.setup.user
#                - sylius.behat.context.setup.zone

                - sylius.behat.context.transform.cart
                - sylius.behat.context.transform.lexical
                - sylius.behat.context.transform.product
                - sylius.behat.context.transform.shared_storage
                - sylius.behat.context.transform.shipping_category

                - sylius.behat.context.api.shop.cart

            filters:
                tags: "@shopping_cart && @api"
