language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script: composer install --prefer-source --no-interaction

script: bin/phpspec run -fpretty --verbose

notifications:
    irc: "irc.freenode.org#sylius-dev"
