Sylius\Component\Product\Model\ProductVariant:
    exclusion_policy: ALL
    xml_root_name: variant
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
            groups: [Default, Detailed]
        code:
            expose: true 
            type: string 
            groups: [Detailed, Default] 
        position:
            expose: true 
            type: integer 
            groups: [Detailed, Default] 
        optionValues:
            expose: true 
            type: array 
            groups: [Detailed, Default] 
        translations:
            expose: true 
            type: array 
            groups: [Detailed, Default] 
    relations:
        - rel: self
          href:
            route: sylius_api_product_variant_show
            parameters:
                id: expr(object.getId())
                productId: expr(object.getProduct().getId())
                version: 1
            exclusion:
                groups: [Detailed]
        - rel: product
          href:
            route: sylius_api_product_show
            parameters:
                id: expr(object.getProduct().getId())
                version: 1
