Sylius\Component\Product\Model\ProductAssociationType:
    exclusion_policy: ALL
    xml_root_name: product-association-type
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
            groups: [Default, Detailed]
        code:
            expose: true
            type: string
            groups: [Default, Detailed]
        translations:
            expose: true
            type: array
            groups: [Default, Detailed]
    virtual_properties:
        getName:
            serialized_name: name
