Sylius\Component\Product\Model\Product:
    exclusion_policy: ALL
    xml_root_name: product
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
            groups: [Default, Detailed]
        code:
            expose: true
            type: string
            groups: [Default, Detailed]
        channels:
            expose: true
            type: array
            groups: [Default, Detailed]
        options:
            expose: true
            type: array
            groups: [Default, Detailed]
        attributes:
            expose: true
            type: array
            groups: [Detailed]
        associations:
            expose: true
            type: array
            groups: [Detailed]
        variants:
            expose: true
            type: array
            groups: [Detailed]
        translations:
            expose: true
            type: array
            groups: [Detailed]
        availableOn:
            expose: true
            type: DateTime
            groups: [Detailed]
        availableUntil:
            expose: true
            type: DateTime
            groups: [Detailed]
    virtual_properties:
        getName:
            serialized_name: name
    relations:
        - rel: self
          href:
            route: sylius_api_product_show
            parameters:
                id: expr(object.getId())
                version: 1
            exclusion:
                groups: [Detailed]
