Sylius\Component\Product\Model\ProductOptionValue:
    exclusion_policy: ALL
    xml_root_name: option-value
    properties:
        code:
            expose: true
            type: string
            groups: [Default, Detailed]
        value:
            expose: true
            type: string
            groups: [Detailed]
    virtual_properties:
        getName:
            serialized_name: name
