Sylius\Component\Product\Model\Product:
    exclusion_policy: ALL
    xml_root_name: product
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
        description:
            expose: true
            type: string
        attributes:
            expose: true
            max_depth: 2
        createdAt:
            expose: true
            type: DateTime
        updatedAt:
            expose: true
            type: DateTime
        translations:
            expose: true
            type: array
    relations:
        - rel: self
          href:
                route: sylius_api_product_show
                parameters:
                    id: expr(object.getId())
                    version: 1
        - rel: variants
          exclusion:
                exclude_if: expr(!object.hasVariants())
          href:
                route: sylius_api_product_variant_index
                parameters:
                    productId: expr(object.getId())
                    version: 1
