Sylius\Component\Product\Model\ProductOption:
    exclusion_policy: ALL
    xml_root_name: product-option
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
            gorups: [Default, Detailed]
        code:
            exopse: true
            type: string
            gorups: [Default, Detailed]
        position:
            expose: true
            type: integer
            gorups: [Default, Detailed]
        values:
            expose: true
            type: array
            gorups: [Detailed]
