Sylius\Component\User\Model\User:
    exclusion_policy: ALL
    xml_root_name: sylius_user
    properties:
        id:
            expose: true
            type: int
        email:
            expose: true
            type: string
        emailCanonical:
            expose: true
            type: string
        username:
            expose: true
            type: string
        usernameCanonical:
            expose: true
            type: string
        enabled:
            expose: true
            type: boolean
        first_name:
            expose: true
            type: string
        last_name:
            expose: true
            type: string
        roles:
            expose: true
            type: array
