Sylius\Component\Taxonomy\Model\Taxon:
    exclusion_policy: ALL
    xml_root_name: taxon
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
            groups: [Default, Detailed]
        code:
            expose: true
            type: string
            groups: [Default, Detailed]
        children:
            expose: true
            type: array
            groups: [Detailed]
        root:
            expose: true
            groups: [Default, Detailed]
        parent:
            expose: true
            groups: [Default, Detailed]
        left:
            expose: true
            type: integer
            groups: [Detailed]
        right:
            expose: true
            type: integer
            groups: [Detailed]
        level:
            expose: true
            type: integer
            groups: [Detailed]
        position:
            expose: true
            type: integer
            groups: [Default, Detailed]
        translations:
            expose: true
            type: array
            groups: [Default, Detailed]
