# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

cached:
    extensions:
        FriendsOfBehat\SymfonyExtension:
            kernel:
                bootstrap: config/bootstrap.php
                debug: false
                env: test_cached
