finite_finite:
    sylius_order_shipping:
        class:         %sylius.model.order.class%
        property_path: shippingState
        graph:         sylius_order_shipping
        states:
            checkout:
                type: initial
            onhold:            ~
            ready:             ~
            backordered:       ~
            partially_shipped: ~
            shipped:           ~
            cancelled:         ~
            returned:
                type: final
        transitions:
            hold:
                from: [checkout]
                to:   onhold
            create:
                from: [checkout, onhold]
                to:   ready
            ship:
                from: [ready, partially_shipped]
                to:   shipped
            ship_partially:
                from: [ready, partially_shipped]
                to:   partially_shipped
            return:
                from: [partially_shipped, shipped]
                to:   returned

    sylius_order_payment:
        class:         %sylius.model.order.class%
        property_path: paymentState
        graph:         sylius_order_payment
        states:
            new:
                type: initial
            pending:    ~
            processing: ~
            completed:  ~
            failed:     ~
            void:       ~
            cancelled:  ~
            refunded:
                type: final
        transitions:
            create:
                from: [new]
                to:   pending
            process:
                from: [new, pending]
                to:   processing
            complete:
                from: [pending, processing]
                to:   completed
            fail:
                from: [pending, processing]
                to:   failed
            cancel:
                from: [new, pending, processing]
                to:   cancelled
            refund:
                from: [completed]
                to:   refunded

    sylius_payment:
        callbacks:
            after:
                test: { on: 'complete', do: [@sylius.callback.order_payment, 'updateOrderOnPayment'], args: ['object'] }

    sylius_order:
        callbacks:
            after:
                sylius_inventory: { on: 'confirm', do: [@sylius.order_processing.inventory_handler, 'updateInventory'],      args: ['object'] }
                sylius_shipment:  { on: 'confirm', do: [@sylius.processor.shipment_processor,       'updateShipmentStates'], args: ['object.getShipments()', '"prepare"'] }
                sylius_coupon:    { on: 'confirm', do: [@sylius.callback.coupon_usage,              'incrementCouponUsage'], args: ['object'] }

    sylius_inventory_unit:
        callbacks:
            after:
                sylius_sync_shipping: { to: '-sold', do: [@finite.callback.cascade_transition, 'apply'], args: ['object', ~, '"sylius_shipping_item"'] }
