# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

default:
    suites:
        cli_removing_locale:
            contexts:    
                - sylius.behat.context.hook.doctrine_orm

                - sylius.behat.context.cli.remove_locale
                - sylius.behat.context.cli.cancel_unpaid_orders

                - sylius.behat.context.transform.address
                - sylius.behat.context.transform.channel
                - sylius.behat.context.transform.customer
                - sylius.behat.context.transform.lexical
                - sylius.behat.context.transform.payment
                - sylius.behat.context.transform.product
                - sylius.behat.context.transform.shared_storage
                - sylius.behat.context.transform.shipping_method
                - sylius.behat.context.transform.order
                
                - sylius.behat.context.setup.locale
                - sylius.behat.context.setup.order
                - sylius.behat.context.setup.channel
                - sylius.behat.context.setup.product
                - sylius.behat.context.setup.shipping
                - sylius.behat.context.setup.payment

                - sylius.behat.context.domain.managing_orders

            filters:
                tags: "@removing_locale&&@cli"
