framework:
    translator: { fallbacks: ["%locale%", "en"] }
    secret: "%secret%"
    router:
        resource: "%kernel.project_dir%/app/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form: true
    csrf_protection: true
    validation: { enable_annotations: true }
    templating: { engines: ["twig"] }
    default_locale: "%locale%"
    session:
        handler_id: ~
