framework:
    secret: '%env(APP_SECRET)%'
    form: true
    csrf_protection: true
    templating: { engines: ["twig"] }
    session:
        handler_id: ~
    serializer:
        enabled: true
        enable_annotations: false
        mapping:
            paths:
                - '%kernel.project_dir%/src/Sylius/Bundle/ApiBundle/Resources/config/serializer/'
