language: php

php:
  - 5.3
  - 5.4
  - 5.5

matrix:
    allow_failures:
        - php: 5.5

before_script: 
    - cp sylius/config/container/parameters.yml.dist sylius/config/container/parameters.yml
    - composer install --dev --prefer-source > /dev/null
    - sylius/console do:da:cr -e=testing > /dev/null
    - sylius/console do:sc:cr -e=testing > /dev/null

script: 
    - bin/behat -f progress --no-snippets

notifications:
  email: "travis-ci@sylius.org"
  irc:   "irc.freenode.org#sylius-dev"
