language: php

env:
    global:
        - SYLIUS_CACHE_DIR=$HOME/.sylius-cache
        - SYLIUS_BUILD_DIR=etc/build

cache:
    directories:
        - bin
        - vendor
        - $SYLIUS_CACHE_DIR

sudo: false

addons:
    apt:
        sources:
            - google-chrome
        packages:
            - google-chrome-stable

services:
    - memcached

php:
    - 7.0
    - 5.6
    - 5.5

before_install:
    - phpenv config-rm xdebug.ini || true

    - mkdir -p $SYLIUS_CACHE_DIR

    - etc/travis/prepare-memcached-extension

    - phpenv config-add etc/travis/before-install-php.ini

    - composer self-update

    # Add Github OAuth token to Composer config if that variable exists
    - if [[ ! -z "$GITHUB_OAUTH_TOKEN" ]]; then composer config -g github-oauth.github.com "$GITHUB_OAUTH_TOKEN" >/dev/null 2>&1; fi

install:
    - composer install --no-interaction --prefer-dist --no-scripts

    - composer run-script travis-build --no-interaction

before_script:
    - phpenv config-add etc/travis/before-script-php.ini

    - app/console doctrine:database:create --env=test_cached

    - app/console cache:warmup --env=test_cached --no-debug

    - app/console doctrine:schema:create --env=test_cached
    - app/console doctrine:phpcr:repository:init --env=test_cached

    - app/console assets:install --env=test_cached --no-debug
    - app/console assetic:dump --env=test_cached --no-debug

    # Debug informations, PHP version & PHP configuration
    # Its needed to remove the line with secret ariable, as it is listed in _SERVER variables
    - php -v
    - php -i | grep -v GITHUB_OAUTH_TOKEN

script:
    - composer validate
    - if [[ $TRAVIS_PHP_VERSION = 7.* ]]; then etc/travis/check-sylius-cs; fi;
    - if [[ $TRAVIS_PHP_VERSION = 7.* ]]; then bin/kawaii gherkin:check --align=left features/; fi;

    - bin/phpspec run --no-interaction -f dot
    - bin/phpunit

    - etc/travis/prepare-javascript
    - bin/behat --strict -f progress -p cached || if [[ $? -eq 1 ]]; then bin/behat --strict -f progress -p cached --rerun; fi # Do not rerun on fatal error (255) or passed tests (0)

before_cache:
    - yes 'Y' | rm -fr vendor/symfony-cmf/create-bundle/Resources/public/vendor/*

after_failure:
    - export IMGUR_API_KEY=4907fcd89e761c6b07eeb8292d5a9b2a
    - vendor/lakion/mink-debug-extension/travis/tools/upload-textfiles "$SYLIUS_BUILD_DIR/*.log"
    - vendor/lakion/mink-debug-extension/travis/tools/upload-screenshots "$SYLIUS_BUILD_DIR/*.png"
