# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_api_checkout_proceed:
    path: /{orderId}
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.checkout:proceedAction
