sylius_product:
    resource: @SyliusProductBundle/Resources/config/routing/product.yml
    prefix: /products

sylius_property:
    resource: @SyliuspropertyBundle/Resources/config/routing/property.yml
    prefix: /properties

sylius_prototype:
    resource: @SyliusprototypesBundle/Resources/config/routing/prototype.yml
    prefix: /prototypes
