# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

default:
    suites:
        api_checkout:
            contexts:
                - sylius.behat.context.hook.doctrine_orm

                - sylius.behat.context.transform.address
                - sylius.behat.context.transform.cart
                - sylius.behat.context.transform.lexical
                - sylius.behat.context.transform.product

                - sylius.behat.context.setup.cart
                - sylius.behat.context.setup.channel
                - sylius.behat.context.setup.product
                - sylius.behat.context.setup.shipping

                - sylius.behat.context.api.shop.checkout

            filters:
                tags: "@checkout && @api"
