sylius_admin_locale:
    resource: |
        alias: sylius.locale
        section: admin
        templates: SyliusAdminBundle:Crud
        except: ['show', 'update', 'delete']
        redirect: index
        grid: sylius_admin_locale
        vars:
            all:
                subheader: sylius.ui.manage_locale
                templates:
                    form: SyliusAdminBundle:Locale:_form.html.twig
            index:
                icon: translate
    type: sylius.resource
