sylius_admin_product_option:
    resource: |
        alias: sylius.product_option
        section: admin
        templates: SyliusAdminBundle:Crud
        except: ['show']
        redirect: update
        grid: sylius_admin_product_option
        vars:
          all:
              subheader: sylius.ui.manage_product_option
              templates:
                  form: SyliusAdminBundle:ProductOption:_form.html.twig
          index:
              icon: options
    type: sylius.resource
