sylius_admin_promotion:
    resource: |
        alias: sylius.promotion
        section: admin
        templates: SyliusAdminBundle:Crud
        except: ['show']
        redirect: update
        grid: sylius_admin_promotion
        vars:
            all:
                templates:
                    form: SyliusAdminBundle:Promotion:_form.html.twig
            index:
                icon: in cart
    type: sylius.resource
