sylius_admin_taxon:
    resource: |
        alias: sylius.taxon
        section: admin
        templates: SyliusAdminBundle:Crud
        except: ['show', 'delete']
        redirect: update
        grid: sylius_admin_taxon
        vars:
            all:
                subheader: sylius.ui.manage_taxons
                templates:
                    form: SyliusAdminBundle:Taxon:_form.html.twig
            index:
                icon: folder
    type: sylius.resource
