sylius_admin_taxon:
    resource: |
        alias: sylius.taxon
        section: admin
        templates: SyliusAdminBundle:Crud
        only: ['update', 'delete']
        redirect: update
        vars:
            all:
                templates:
                    form: SyliusAdminBundle:Taxon:_form.html.twig
                    subheader: sylius.ui.manage_taxons
                    icon: folder
    type: sylius.resource

sylius_admin_taxon_index:
    path: /taxons/
    methods: [GET]
    defaults:
        _controller: sylius.controller.taxon:indexAction
        _sylius:
            template: SyliusAdminBundle:Taxon:index.html.twig
            section: admin
            repository:
                method: findRootNodes
    host: "localhost"

sylius_admin_taxon_create:
    path: /taxons/new
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.taxon:createAction
        _sylius:
            template: SyliusAdminBundle:Taxon:create.html.twig
            section: admin
            vars:
                templates:
                    form: SyliusAdminBundle:Taxon:_form.html.twig
