# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_taxation_category:
    resource: @SyliusTaxationBundle/Resources/config/routing/category.yml
    prefix: /tax-categories

sylius_taxation_rate:
    resource: @SyliusTaxationBundle/Resources/config/routing/rate.yml
    prefix: /tax-rates
