# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_fixtures:
    suites:
        default:
            listeners:
                orm_purger: ~
            fixtures:
                locale:
                    options:
                        locales:
                            - en_US
                            - en_GB
                            - es_ES
                            - pl_PL

                currency:
                    options:
                        currencies:
                            - EUR
                            - USD
                            - GBP
                            - CHF

                geographical:
                    options:
                        provinces:
                            US:
                                US-CA: California
                                US-OR: Oregon
                                US-WA: Washington
                                US-AL: Alabama
                                US-TN: Tennessee
                        zones:
                            US-WEST-COAST:
                                name: "West coast of USA"
                                provinces:
                                    - US-CA
                                    - US-OR
                                    - US-WA
                            EUROPE:
                                name: "European countries"
                                countries:
                                    - PL
                                    - DE
                                    - FR
                            YO-DAWG:
                                name: "Zone in a zone"
                                zones:
                                    - US-WEST-COAST
                                    - EUROPE

                payment_method:
                    options:
                        payment_methods: 10

                shipping_category:
                    options:
                        shipping_categories: 10

                shipping_method:
                    options:
                        shipping_methods: 20

                channel:
                    options:
                        channels: 3
