# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

parameters:
    sylius.inventory.backorders_enabled: true
    sylius.inventory.tracking_enabled: true
    sylius.inventory.holding.duration: 15 minutes
    sylius.order.allow_guest_order: false
    sylius.order.pending.duration: 3 hours
    sylius.cache:
        type: file_system
    sylius.uploader.filesystem: sylius_image
