# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

imports:
    - { resource: "state_machine/sylius_order_checkout.yml" }
    - { resource: "state_machine/sylius_order_shipping.yml" }
    - { resource: "state_machine/sylius_order_payment.yml" }
    - { resource: "state_machine/sylius_order.yml" }
    - { resource: "state_machine/sylius_shipment.yml" }
    - { resource: "state_machine/sylius_payment.yml" }
    - { resource: "state_machine/sylius_review.yml" }
