sylius_core:
    driver: doctrine/orm
    emails:
        enabled: false

sylius_installer:
    classes:
        user:
            model: Sylius\Bundle\CoreBundle\Model\User

sylius_money:
    currency: %sylius.currency%
    locale: %sylius.locale%

sylius_cart:
    resolver: sylius.cart_item_resolver.default
    classes:
        item:
            form: Sylius\Bundle\CoreBundle\Form\Type\CartItemType
        cart:
            form: Sylius\Bundle\CoreBundle\Form\Type\CartType

sylius_settings: ~

sylius_taxonomies:
    classes:
        taxonomy:
            model: Sylius\Bundle\CoreBundle\Model\Taxonomy
            form: Sylius\Bundle\CoreBundle\Form\Type\TaxonomyType
        taxon:
            model: Sylius\Bundle\CoreBundle\Model\Taxon
            form: Sylius\Bundle\CoreBundle\Form\Type\TaxonType

sylius_product:
    classes:
        product:
            model: Sylius\Bundle\CoreBundle\Model\Product
            controller: Sylius\Bundle\CoreBundle\Controller\ProductController
            repository: Sylius\Bundle\CoreBundle\Repository\ProductRepository
            form: Sylius\Bundle\CoreBundle\Form\Type\ProductType

sylius_variable_product:
    classes:
        variant:
            model: Sylius\Bundle\CoreBundle\Model\Variant
            repository: Sylius\Bundle\CoreBundle\Repository\VariantRepository
            form: Sylius\Bundle\CoreBundle\Form\Type\VariantType

sylius_taxation:
    classes:
        tax_rate:
            model: Sylius\Bundle\CoreBundle\Model\TaxRate
            form: Sylius\Bundle\CoreBundle\Form\Type\TaxRateType

sylius_shipping:
    classes:
        shipment:
            model: Sylius\Bundle\CoreBundle\Model\Shipment
            repository: Sylius\Bundle\CoreBundle\Repository\ShipmentRepository
        shipment_item:
            model: Sylius\Bundle\CoreBundle\Model\InventoryUnit
        shipping_method:
            model: Sylius\Bundle\CoreBundle\Model\ShippingMethod
            form: Sylius\Bundle\CoreBundle\Form\Type\ShippingMethodType

sylius_promotions:
    classes:
        promotion_subject:
            model: %sylius.model.order.class%

sylius_inventory:
    backorders: %sylius.inventory.backorders_enabled%
    track_inventory: %sylius.inventory.tracking_enabled%
    classes:
        inventory_unit:
            model: Sylius\Bundle\CoreBundle\Model\InventoryUnit
        stockable:
            model: %sylius.model.variant.class%

sylius_payments:
    classes:
        payment:
            controller: Sylius\Bundle\CoreBundle\Controller\PaymentController
    gateways:
        dummy: Test
        stripe: Stripe
        be2bill: Be2Bill

sylius_payum: ~

sylius_addressing:
    classes:
        address:
            controller: Sylius\Bundle\WebBundle\Controller\Frontend\Account\AddressController

sylius_order:
    classes:
        order:
            model: Sylius\Bundle\CoreBundle\Model\Order
            controller: Sylius\Bundle\CoreBundle\Controller\OrderController
            repository: Sylius\Bundle\CoreBundle\Repository\OrderRepository
            form: Sylius\Bundle\CoreBundle\Form\Type\OrderType
        order_item:
            model: Sylius\Bundle\CoreBundle\Model\OrderItem

sylius_resource:
    resources:
        sylius.user:
            driver: doctrine/orm
            classes:
                model: Sylius\Bundle\CoreBundle\Model\User
                controller: Sylius\Bundle\CoreBundle\Controller\UserController
                repository: Sylius\Bundle\CoreBundle\Repository\UserRepository
        sylius.group:
            driver: doctrine/orm
            classes:
                model: Sylius\Bundle\CoreBundle\Model\Group
        sylius.locale:
            driver: doctrine/orm
            classes:
                model: Sylius\Bundle\CoreBundle\Model\Locale
                controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController
        sylius.block:
            driver: doctrine/phpcr-odm
            classes:
                model: Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\SimpleBlock
        sylius.page:
            driver: doctrine/phpcr-odm
            classes:
                model: Symfony\Cmf\Bundle\ContentBundle\Doctrine\Phpcr\StaticContent
                repository: Sylius\Bundle\CoreBundle\Repository\PageRepository

doctrine_cache:
    providers:
        sylius_settings: %sylius.cache%

knp_gaufrette:
    adapters:
        sylius_image:
            local:
                directory:  %kernel.root_dir%/../web/media/image
                create:     true
    filesystems:
        sylius_image:
            adapter: sylius_image

liip_imagine:
    data_root: %kernel.root_dir%/../web/media/image
    filter_sets:
        sylius_small:
            filters:
                thumbnail: { size: [120, 90], mode: outbound }
        sylius_medium:
            filters:
                thumbnail: { size: [240, 180], mode: outbound }
        sylius_large:
            filters:
                thumbnail: { size: [640, 480], mode: outbound }

knp_snappy:
    pdf:
        enabled:    true
        binary:     /usr/bin/wkhtmltopdf
        options:    []
    image:
        enabled:    true
        binary:     /usr/bin/wkhtmltoimage
        options:    []

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.block.service.text: ~

stof_doctrine_extensions:
    default_locale: %sylius.locale%
    orm:
        default:
            tree: true
            sluggable: true
            timestampable: true
            softdeleteable: true
            loggable: true
            sortable: true

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: %sylius.model.user.class%
    group:
        group_class: Sylius\Bundle\CoreBundle\Model\Group
    profile:
        form:
            type: sylius_user_profile
    registration:
        form:
            type: sylius_user_registration

hwi_oauth:
    firewall_name: main
    resource_owners:
        amazon:
            type:          amazon
            client_id:     %sylius.oauth.amazon.clientid%
            client_secret: %sylius.oauth.amazon.clientsecret%
        facebook:
            type:          facebook
            client_id:     %sylius.oauth.facebook.clientid%
            client_secret: %sylius.oauth.facebook.clientsecret%
        google:
            type:          google
            client_id:     %sylius.oauth.google.clientid%
            client_secret: %sylius.oauth.google.clientsecret%
            scope:         "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"
