imports:
    - { resource: "sylius/sylius_addressing.yml" }
    - { resource: "sylius/sylius_association.yml" }
    - { resource: "sylius/sylius_channel.yml" }
    - { resource: "sylius/sylius_content.yml" }
    - { resource: "sylius/sylius_core.yml" }
    - { resource: "sylius/sylius_inventory.yml" }
    - { resource: "sylius/sylius_locale.yml" }
    - { resource: "sylius/sylius_mailer.yml" }
    - { resource: "sylius/sylius_money.yml" }
    - { resource: "sylius/sylius_order.yml" }
    - { resource: "sylius/sylius_payment.yml" }
    - { resource: "sylius/sylius_pricing.yml" }
    - { resource: "sylius/sylius_product.yml" }
    - { resource: "sylius/sylius_promotion.yml" }
    - { resource: "sylius/sylius_resource.yml" }
    - { resource: "sylius/sylius_review.yml" }
    - { resource: "sylius/sylius_shipping.yml" }
    - { resource: "sylius/sylius_taxation.yml" }
    - { resource: "sylius/sylius_taxonomy.yml" }
    - { resource: "sylius/sylius_user.yml" }
    - { resource: "sylius/sylius_customer.yml" }
