# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

imports:
    - { resource: "parameters.yml" }
    - { resource: "security.yml" }

    - { resource: "@SyliusCoreBundle/Resources/config/config.yml" }
    - { resource: "@SyliusWebBundle/Resources/config/config.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/config.yml" }

framework:
    translator: { fallback: "%locale%" }
    secret: "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form: true
    csrf_protection: true
    validation: { enable_annotations: true }
    templating: { engines: ["twig"] }
    default_locale: "%locale%"
    trusted_proxies: ~
    session:
        handler_id: ~

doctrine:
    dbal:
        driver: "%database_driver%"
        host: "%database_host%"
        port: "%database_port%"
        dbname: "%database_name%"
        user: "%database_user%"
        password: "%database_password%"
        charset: UTF8

swiftmailer:
    transport: "%mailer_transport%"
    host: "%mailer_host%"
    username: "%mailer_user%"
    password: "%mailer_password%"

twig:
    form_themes:
        - "SyliusWebBundle:Common:forms.html.twig"
        - "SyliusResourceBundle::forms.html.twig"

fos_rest:
    view:
        formats:
            json: true
            xml:  true
        empty_content: 204
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json', 'xml'], fallback_format: json, prefer_extension: true }
            - { path: '^/', stop: true }
