# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

imports:
    - { resource: config.yml }

parameters:
    sylius.order.allow_guest_order: true

framework:
    test: ~
    default_locale: "en"
    session:
        storage_id: session.storage.mock_file

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        dbname: %sylius.database.name%_test
        path:   %sylius.database.path%
        driver_class: Sylius\Bundle\CoreBundle\Test\MySqlDriver

sylius_money:
    currency: EUR
    locale:   en_US

sylius_payment:
    gateways:
        cc:     Credit Card
        test:   Test
        stripe: Stripe
        paypal_express_checkout: Paypal Express Checkout

sylius_rbac:
    authorization_checker: sylius.authorization_checker.toggleable

sylius_channel:
    fake_channel_support: true

sylius_theme:
    sources:
        filesystem:
            locations:
                - "%kernel.root_dir%/themes"
                - "%kernel.root_dir%/../vendor/sylius/themes"
                - "%kernel.cache_dir%/_themes"

doctrine_cache:
    providers:
        sylius_settings:
            type: array

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: error

twig:
    exception_controller: 'Sylius\Bundle\CoreBundle\Controller\VerboseExceptionController::showAction'

payum:
    gateways:
        paypal_express_checkout:
            paypal_express_checkout_nvp:
                username: TEST
                password: TEST
                signature: TEST
                sandbox: true
