# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

default:
    suites:
        api_customer_requesting_contact:
            contexts:
                - sylius.behat.context.hook.doctrine_orm
                - sylius.behat.context.hook.email_spool

                - sylius.behat.context.transform.shared_storage

                - sylius.behat.context.setup.channel
                - sylius.behat.context.setup.shop_security
                - sylius.behat.context.setup.user

                - sylius.behat.context.api.shop.contact_request
                - sylius.behat.context.ui.email

            filters:
                tags: "@requesting_contact&&@api"
