# This file is part of the Sylius package.
# (c) Sylius Sp. z o.o.

default:
    suites:
        api_managing_customers:
            contexts:
                - sylius.behat.context.hook.doctrine_orm

                - sylius.behat.context.transform.customer
                - sylius.behat.context.transform.customer_group
                - sylius.behat.context.transform.shared_storage

                - sylius.behat.context.setup.admin_api_security
                - sylius.behat.context.setup.customer
                - sylius.behat.context.setup.customer_group

                - sylius.behat.context.api.admin.managing_customers
                - sylius.behat.context.api.admin.response
                - sylius.behat.context.api.admin.save

            filters:
                tags: "@managing_customers&&@api"
            javascript: false
