finite_finite:
    sylius_order:
        class:         %sylius.model.order.class%
        property_path: state
        graph:         sylius_order
        states:
            cart:
                type: initial
            pending:   ~
            released:  ~
            confirmed: ~
            shipped:   ~
            abandoned: ~
            cancelled:
                type: final
            returned:
                type: final
        transitions:
            create:
                from: [cart]
                to:   pending
            release:
                from: [pending]
                to:   released
            confirm:
                from: [cart, pending, released]
                to:   confirmed
            ship:
                from: [confirmed]
                to:   shipped
            abandon:
                from: [cart, pending]
                to:   abandoned
            cancel:
                from: [confirmed]
                to:   cancelled
            return:
                from: [shipped]
                to:   returned
        callbacks:
            after:
                sylius_complete: { on: 'create', do: [@sylius.callback.complete_order,           'completeOrder'], args: ['object'] }
                sylius_number:   { on: 'create', do: [@sylius.sequence.doctrine_number_listener, 'enableEntity'],  args: ['object'] }
