finite_finite:
    sylius_order:
        class:         %sylius.model.order.class%
        property_path: state
        graph:         sylius_order
        states:
            cart:
                type: initial
            pending:   ~
            confirmed: ~
            shipped:   ~
            abandoned: ~
            cancelled: ~
            returned:
                type: final
        transitions:
            create:
                from: [cart]
                to:   pending
            confirm:
                from: [cart, pending]
                to:   confirmed
            ship:
                from: [confirmed]
                to:   shipped
            abandon:
                from: [cart, pending]
                to:   abandoned
            cancel:
                from: [confirmed]
                to:   cancelled
            return:
                from: [shipped]
                to:   returned
        callbacks:
            before:
                - { on: 'create', do: [@sylius.sequence.doctrine_number_listener, 'enableEntity'], args: ['object'] }
