# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

default:
    suites:
        api_managing_product_options:
            contexts:
                - sylius.behat.context.hook.doctrine_orm

                - sylius.behat.context.transform.lexical
                - sylius.behat.context.transform.locale
                - sylius.behat.context.transform.product_option
                - sylius.behat.context.transform.shared_storage

                - sylius.behat.context.setup.locale
                - sylius.behat.context.setup.product_option
                - sylius.behat.context.setup.admin_security

                - sylius.behat.context.api.admin.managing_product_options

            filters:
                tags: "@managing_product_options && @api"
        ui_managing_product_options:
            contexts:
                - sylius.behat.context.hook.doctrine_orm

                - sylius.behat.context.transform.lexical
                - sylius.behat.context.transform.locale
                - sylius.behat.context.transform.product_option
                - sylius.behat.context.transform.shared_storage

                - sylius.behat.context.setup.locale
                - sylius.behat.context.setup.product_option
                - sylius.behat.context.setup.admin_security

                - sylius.behat.context.ui.admin.managing_product_options
                - sylius.behat.context.ui.admin.notification

            filters:
                tags: "@managing_product_options && @ui"
