winzou_state_machine:
    sylius_payment:
        callbacks:
            after:
                process_order:
                    on: ["fail", "cancel"]
                    do: ["@sylius.order_processing.order_payment_processor", "process"]
                    args: ["object.getOrder()"]
                update_order_payment_state:
                    on: ["complete"]
                    do: ["@sylius.state_resolver.order_payment", "resolve"]
                    args: ["object.getOrder()"]
