# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_api:
    resource: .
    type: api_platform
    prefix: /

sylius_api_admin_authentication_token:
    path: /admin/authentication-token
    methods: ['POST']
