# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_api:
    resource: .
    type: api_platform
    prefix: /

api_authentication_token:
    path: /authentication-token
    methods: ['POST']
