# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_content:
    driver: doctrine/phpcr-odm
    resources:
        static_content:
            classes:
                repository: Sylius\Bundle\ContentBundle\Doctrine\ODM\PHPCR\StaticContentRepository
                form:
                    choice: Sylius\Bundle\ContentBundle\Form\Type\StaticContentChoiceType
