# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_customer:
    resources:
        customer:
            classes:
                model: Sylius\Component\Core\Model\Customer
                repository: Sylius\Bundle\CoreBundle\Doctrine\ORM\CustomerRepository
                form:
                    default: Sylius\Bundle\CoreBundle\Form\Type\Customer\CustomerType
