# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_taxonomy:
    resources:
        taxon:
            classes:
                model: Sylius\Component\Core\Model\Taxon
                repository: Sylius\Bundle\TaxonomyBundle\Doctrine\ORM\TaxonRepository
                form:
                    default: Sylius\Bundle\CoreBundle\Form\Type\Taxon\TaxonType
