# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_review:
    resources:
        product:
            subject: "%sylius.model.product.class%"
            review:
                classes:
                    model: Sylius\Component\Core\Model\ProductReview
                    form:
                        default: Sylius\Bundle\CoreBundle\Form\Type\Product\ProductReviewType
            reviewer:
                classes:
                    model: "%sylius.model.customer.class%"
