# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_order:
    resources:
        order:
            classes:
                model: Sylius\Component\Core\Model\Order
                controller: Sylius\Bundle\CoreBundle\Controller\OrderController
                repository: Sylius\Bundle\CoreBundle\Doctrine\ORM\OrderRepository
                form:
                    default: Sylius\Bundle\CoreBundle\Form\Type\Order\OrderType
        order_item:
            classes:
                model: Sylius\Component\Core\Model\OrderItem
                form:
                    default: Sylius\Bundle\CoreBundle\Form\Type\Order\OrderItemType
        order_item_unit:
            classes:
                model: Sylius\Component\Core\Model\OrderItemUnit
