# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

default:
    suites:
        api_managing_orders:
            contexts:
                - sylius.behat.context.hook.calendar
                - sylius.behat.context.hook.doctrine_orm
                - sylius.behat.context.hook.email_spool

                - sylius.behat.context.setup.admin_api_security
                - sylius.behat.context.setup.channel
                - sylius.behat.context.setup.order
                - sylius.behat.context.setup.payment
                - sylius.behat.context.setup.product
                - sylius.behat.context.setup.promotion
                - sylius.behat.context.setup.shipping

                - sylius.behat.context.transform.address
                - sylius.behat.context.transform.channel
                - sylius.behat.context.transform.currency
                - sylius.behat.context.transform.customer
                - sylius.behat.context.transform.lexical
                - sylius.behat.context.transform.order
                - sylius.behat.context.transform.payment
                - sylius.behat.context.transform.product
                - sylius.behat.context.transform.shipping_method
                - sylius.behat.context.transform.shared_storage

                - sylius.behat.context.api.admin.managing_orders

            filters:
                tags: "@managing_orders && @api"
            javascript: false
