Sylius\Component\Core\Model\OrderItem:
    exclusion_policy: ALL
    xml_root_name: order-item
    properties:
        variant:
            expose: true
            groups: [Default, Detailed, DetailedCart]
    relations:
        - rel: order
          exclusion:
            groups: [Default, Detailed, DetailedCart]
          href:
                route: sylius_admin_api_order_show
                parameters:
                    id: expr(object.getOrder().getId())
                    version: 1
        - rel: product
          exclusion:
            exclude_if: expr(!object.getVariant())
            groups: [Default, Detailed, DetailedCart]
          href:
            route: sylius_admin_api_product_show
            parameters:
                code: expr(object.getVariant().getProduct().getCode())
                version: 1
        - rel: variant
          exclusion:
            exclude_if: expr(!object.getVariant())
            groups: [Default, Detailed, DetailedCart]
          href:
            route: sylius_admin_api_product_variant_show
            parameters:
                code: expr(object.getVariant().getCode())
                productCode: expr(object.getVariant().getProduct().getCode())
                version: 1