Sylius\Component\Core\Model\Order:
    exclusion_policy: ALL
    xml_root_name: order
    properties:
        checkoutState:
            expose: true
            type: string
            groups: [Default, Detailed, DetailedCart]
        currencyCode:
            expose: true
            type: string
            groups: [Default, Detailed, DetailedCart]
        localeCode:
            expose: true
            type: string
            groups: [Default, Detailed, DetailedCart]
        shippingAddress:
            expose: true
            groups: [Detailed]
        billingAddress:
            expose: true
            groups: [Detailed]
        shipments:
            expose: true
            groups: [Detailed]
        payments:
            expose: true
            groups: [Detailed]
        customer:
            expose: true
            groups: [Default, Detailed, DetailedCart]
        channel:
            expose: true
            groups: [Default, Detailed, DetailedCart]
        promotionCoupon:
            expose: true
            groups: [Default, Detailed, DetailedCart]
    relations:
        - rel: order
          exclusion:
            groups: [Default, Detailed, DetailedCart]
          href:
                route: sylius_admin_api_order_show
                parameters:
                    id: expr(object.getOrder().getId())
                    version: 1