sylius_grid:
    grids:
        sylius_admin_customer:
            driver:
                name: doctrine/orm
                options:
                    class: %sylius.model.customer.class%
            sorting:
                firstName: asc
            fields:
                first_name:
                    type: string
                    label: sylius.ui.first_name
                last_name:
                    type: string
                    label: sylius.ui.last_name
                email:
                    type: string
                    label: sylius.ui.email
                created_at:
                    type: twig
                    label: sylius.ui.registration_date
                    path: .
                    options:
                        template: SyliusAdminBundle:Customer/Field:createdAt.html.twig
                confirmed:
                    type: twig
                    label: sylius.ui.confirmed
                    path: .
                    options:
                        template: SyliusAdminBundle:Customer/Field:confirmed.html.twig
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
