sylius_grid:
    grids:
        sylius_admin_order:
            driver:
                name: doctrine/orm
                options:
                    class: "%sylius.model.order.class%"
            sorting:
                completedAt: desc
            fields:
                number:
                    type: string
                    label: sylius.ui.number
                date:
                    type: datetime
                    label: sylius.ui.date
                    path: completedAt
                    options:
                        format: d-m-Y H:i:s
                customer:
                    type: twig
                    label: sylius.ui.customer
                    options:
                        template: SyliusAdminBundle:Order/Field:customer.html.twig
                state:
                    type: twig
                    label: sylius.ui.state
                    options:
                        template: SyliusAdminBundle:Order/Field:state.html.twig
                paymentState:
                    type: twig
                    label: sylius.ui.payment_state
                    options:
                        template: SyliusAdminBundle:Order/Field:state.html.twig
                shippingState:
                    type: twig
                    label: sylius.ui.shipping_state
                    options:
                        template: SyliusAdminBundle:Order/Field:state.html.twig
                total:
                    type: twig
                    label: sylius.ui.total
                    path: .
                    options:
                        template: SyliusAdminBundle:Order/Field:total.html.twig
            actions:
                item:
                    show:
                        type: show
                    delete:
                        type: delete
