sylius_grid:
    grids:
        sylius_admin_product_attribute:
            driver:
                name: doctrine/orm
                options:
                    class: "%sylius.model.product_attribute.class%"
            sorting:
                code: asc
            fields:
                code:
                    type: string
                    label: sylius.ui.code
                name:
                    type: string
                    label: sylius.ui.name
                type:
                    type: string
                    label: sylius.ui.type
                updated_at:
                    type: datetime
                    label: sylius.ui.last_update
                    options:
                        format: d-m-Y H:i
            actions:
                main:
                    create:
                        type: create_product_attribute
                item:
                    update:
                        type: update
                    delete:
                        type: delete
