sylius_grid:
    grids:
        sylius_admin_promotion:
            driver:
                name: doctrine/orm
                options:
                    class: "%sylius.model.promotion.class%"
            fields:
                code:
                    type: string
                    label: sylius.ui.code
                name:
                    type: twig
                    label: sylius.ui.name
                    path: .
                    options:
                        template: SyliusAdminBundle:Grid/Field:nameAndDescription.html.twig
                couponBased:
                    type: twig
                    label: sylius.ui.coupons
                    options:
                        template: SyliusAdminBundle:Grid/Field:yesNo.html.twig
                usage:
                    type: twig
                    label: sylius.ui.usage
                    path: .
                    options:
                        template: SyliusAdminBundle:Promotion/Field:usage.html.twig
            filters:
                code:
                    type: string
                    label: sylius.ui.code
                name:
                    type: string
                    label: sylius.ui.name
                couponBased:
                    type: boolean
                    label: sylius.ui.coupons
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
                    manageCoupons:
                        type: manage_coupons
