sylius_grid:
    grids:
        sylius_admin_promotion:
            driver:
                name: doctrine/orm
                options:
                    class: "%sylius.model.promotion.class%"
            fields:
                codeExclusiveAndCouponBased:
                    type: twig
                    label: sylius.ui.code
                    path: .
                    options:
                        template: SyliusAdminBundle:Promotion/Field:codeExclusiveAndCouponBased.html.twig
                nameAndDescription:
                    type: twig
                    label: sylius.ui.name
                    path: .
                    options:
                        template: SyliusAdminBundle:Grid/Field:nameAndDescription.html.twig
                usedWithUsageLimit:
                    type: twig
                    label: sylius.ui.used
                    path: .
                    options:
                        template: SyliusAdminBundle:Promotion/Field:usedWithUsageLimit.html.twig
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete

