sylius_grid:
    grids:
        sylius_admin_shipping_method:
            driver:
                name: doctrine/orm
                options:
                    class: %sylius.model.shipping_method.class%
            fields:
                code:
                    type: string
                    label: sylius.ui.code
                name:
                    type: string
                    label: sylius.ui.name
                zone:
                    type: string
                    label: sylius.ui.zone
                enabled:
                    type: twig
                    label: sylius.ui.enabled
                    options:
                        template: SyliusAdminBundle:Grid/Field:enabled.html.twig
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
