sylius_grid:
    grids:
        sylius_admin_tax_rate:
            driver:
                name: doctrine/orm
                options:
                    class: %sylius.model.tax_rate.class%
            sorting:
                name: asc
            fields:
                category:
                    type: string
                    label: sylius.ui.category
                name:
                    type: string
                    label: sylius.ui.name
                code:
                    type: string
                    label: sylius.ui.code
                zone:
                    type: string
                    label: sylius.ui.zone
                amount:
                    type: twig
                    label: sylius.ui.amount
                    options:
                        template: SyliusAdminBundle:TaxRate/Field:amount.html.twig
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
