# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_flow_start:
    pattern: /{processAlias}/start
    defaults: { _controller: sylius_flow.controller.process:startAction }

sylius_flow_step:
    pattern: /{processAlias}/step/{stepIndex}
    defaults: { _controller: sylius_flow.controller.process:stepAction }
