# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_flow_start:
    pattern: /{scenarioAlias}
    defaults: { _controller: sylius_flow.controller.process:startAction }

sylius_flow_display:
    pattern: /{scenarioAlias}/{stepAlias}
    defaults: { _controller: sylius_flow.controller.process:displayAction }

sylius_flow_forward:
    pattern: /{scenarioAlias}/{stepAlias}/forward
    defaults: { _controller: sylius_flow.controller.process:forwardAction }
