language: php

php:
  - 5.3
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - php: 5.5

env: MONGO_VERSION=1.3.4

services: mongodb

before_script:
  - composer install --dev --prefer-source

script: php bin/phpspec run -f pretty

notifications:
    email: "travis-ci@sylius.org"
    irc:   "irc.freenode.org#sylius-dev"
