Sylius\Component\Core\Model\Promotion:
    exclusion_policy: ALL
    xml_root_name: product
    properties:
        channels:
            expose: true
            type: array
            groups: [Detailed]
