Sylius\Component\Core\Model\PorductTaxon:
    exclusion_policy: ALL
    xml_root_name: product-taxon
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
        position:
            expose: true
            type: integer
