Sylius\Component\Core\Model\ProductImage:
    exclusion_policy: ALL
    xml_root_name: product-image
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
            groups: [Default, Detailed]
        type:
            expose: true
            type: string
            groups: [Default, Detailed]
        owner:
            expose: true
            groups: [Detailed]
