# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_user:
    resources:
        admin:
            user:
                templates: "SyliusWebBundle:Frontend/User"
        shop:
            user:
                templates: "SyliusWebBundle:Frontend/Customer"
