# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_account_order_index:
    path: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.frontend.account.order:indexAction

sylius_account_order_invoice:
    path: /invoice/{number}.pdf
    methods:  [GET]
    defaults:
        _controller: sylius.controller.frontend.account.order:renderInvoiceAction

sylius_account_order_payment_create:
    path: /{number}/payments/create
    methods: [GET]
    defaults:
        _controller: sylius.controller.frontend.account.order:createPaymentAction

sylius_account_order_after_purchase:
    path: /after-purchase
    methods: [GET]
    defaults:
        _controller: sylius.controller.frontend.account.order:afterPurchaseAction

sylius_account_order_purchase:
    path: /{paymentId}/purchase
    methods: [GET]
    defaults:
        _controller: sylius.controller.frontend.account.order:purchaseAction

sylius_account_order_payment_index:
    path: /{number}/payments
    methods: [GET]
    defaults:
        _controller: sylius.controller.frontend.account.order:showPaymentsAction

sylius_account_order_show:
    path: /{number}
    methods: [GET]
    defaults:
        _controller: sylius.controller.frontend.account.order:showAction
