finite_finite:
    sylius_shipment:
        class:         %sylius.model.shipment.class%
        property_path: state
        graph:         sylius_shipment
        states:
            checkout:
                type: initial
            pending:     ~
            onhold:      ~
            ready:       ~
            backordered: ~
            shipped:     ~
            cancelled:
                type: final
            returned:
                type: final
        transitions:
            hold:
                from: [checkout]
                to:   onhold
            release:
                from: [onhold]
                to:   checkout
            prepare:
                from: [checkout, onhold]
                to:   ready
            ship:
                from: [ready]
                to:   shipped
            cancel:
                from: [checkout, onhold, ready, backordered]
                to:   cancelled
            return:
                from: [shipped]
                to:   returned
        callbacks:
            after:
                sylius_sync_items:
                    do:   [@finite.callback.cascade_transition, 'apply']
                    args: ['object.getItems()', 'event', 'null', '"sylius_shipment_item"']

    sylius_shipment_item:
        class:         %sylius.model.shipment_item.class%
        property_path: shippingState
        graph:         sylius_shipment_item
        states:
            checkout:
                type: initial
            onhold:      ~
            ready:       ~
            backordered: ~
            shipped:     ~
            cancelled:
                type: final
            returned:
                type: final
        transitions:
            hold:
                from: [checkout]
                to:   onhold
            release:
                from: [onhold]
                to:   checkout
            backorder:
                from: [checkout, onhold]
                to:   backordered
            prepare:
                from: [checkout, onhold]
                to:   ready
            ship:
                from: [ready]
                to:   shipped
            cancel:
                from: [checkout, onhold, ready, backordered]
                to:   cancelled
            return:
                from: [shipped]
                to:   returned
