# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_partial_product_latest:
    path: /latest
    defaults:
        _controller: sylius.controller.product:indexAction
        _sylius:
            paginate: false
            repository:
                method: findLatest
                arguments: [$limit]
            template: $template
            permission: false
