# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

default:
    suites:
        api_managing_catalog_promotions:
            contexts:
                - sylius.behat.context.hook.doctrine_orm

                - sylius.behat.context.transform.channel
                - sylius.behat.context.transform.shared_storage
                - Sylius\Behat\Context\Transform\CatalogPromotionContext

                - sylius.behat.context.transform.catalog_promotion
                - sylius.behat.context.transform.shared_storage
                
                - sylius.behat.context.setup.admin_api_security
                - sylius.behat.context.setup.catalog_promotion
                - sylius.behat.context.setup.channel

                - sylius.behat.context.api.admin.managing_catalog_promotions

            filters:
                tags: "@managing_catalog_promotions && @api"
