sylius_cart_show:
    pattern: /
    defaults: { _controller: sylius_cart.controller.frontend.cart:showAction }

sylius_cart_save:
    pattern: /save
    defaults: { _controller: sylius_cart.controller.frontend.cart:saveAction }

sylius_cart_clear:
    pattern: /clear
    defaults: { _controller: sylius_cart.controller.frontend.cart:clearAction }

sylius_cart_item_add:
    pattern: /item/add
    defaults: { _controller: sylius_cart.controller.frontend.cart:addItemAction }

sylius_cart_item_remove:
    pattern: /item/remove
    defaults: { _controller: sylius_cart.controller.frontend.cart:removeItemAction }

