sylius_cart_show:
    pattern: /cart
    defaults: { _controller: sylius_carts.controller.frontend.cart:showAction }

sylius_cart_save:
    pattern: /cart/save
    defaults: { _controller: sylius_carts.controller.frontend.cart:saveAction }

sylius_cart_clear:
    pattern: /cart/clear
    defaults: { _controller: sylius_carts.controller.frontend.cart:clearAction }

sylius_cart_item_add:
    pattern: /cart/item/add
    defaults: { _controller: sylius_carts.controller.frontend.cart:addItemAction }

sylius_cart_item_remove:
    pattern: /cart/item/{id}/remove
    defaults: { _controller: sylius_carts.controller.frontend.cart:removeItemAction }

