finite_finite:
    sylius_inventory_unit:
        class:         %sylius.model.inventory_unit.class%
        property_path: inventoryState
        graph:         sylius_inventory_unit
        states:
            checkout:
                type: initial
            onhold:      ~
            sold:       ~
            backordered: ~
            returned:
                type: final
        transitions:
            hold:
                from: [checkout]
                to:   onhold
            release:
                from: [onhold]
                to:   checkout
            backorder:
                from: [checkout, onhold]
                to:   backordered
            sell:
                from: [checkout, onhold, backordered]
                to:   sold
            return:
                from: [shipped]
                to:   returned
