# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_taxation_category_index:
    pattern: /
    defaults:
        _controller: sylius_taxation.controller.category:indexAction
        _sylius.resource:
            sortable: true
            sorting:
                name: desc

sylius_taxation_category_create:
    pattern: /create
    defaults:
        _controller: sylius_taxation.controller.category:createAction

sylius_taxation_category_update:
    pattern: /{id}/update
    defaults:
        _controller: sylius_taxation.controller.category:updateAction

sylius_taxation_category_delete:
    pattern: /{id}/delete
    defaults:
        _controller: sylius_taxation.controller.category:deleteAction

sylius_taxation_category_show:
    pattern: /{id}
    defaults:
        _controller: sylius_taxation.controller.category:showAction
