# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

default:
    suites:
        ui_checkout:
            contexts_as_services:
                - sylius.behat.context.hook.doctrine_orm

                - sylius.behat.context.transform.addressing
                - sylius.behat.context.transform.lexical
                - sylius.behat.context.transform.product

                - sylius.behat.context.setup.channel
                - sylius.behat.context.setup.security
                - sylius.behat.context.setup.product

                - sylius.behat.context.ui.checkout
                - sylius.behat.context.ui.shop.cart
            filters:
                tags: "@checkout && @ui"
