# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

default:
    suites:
        ui_managing_catalog_promotions:
            contexts:
                - sylius.behat.context.hook.doctrine_orm

                - sylius.behat.context.transform.channel
                - Sylius\Behat\Context\Transform\CatalogPromotionContext
                
                - sylius.behat.context.setup.admin_security
                - sylius.behat.context.setup.channel
                - Sylius\Behat\Context\Setup\CatalogPromotionContext

                - Sylius\Behat\Context\Ui\Admin\ManagingCatalogPromotionsContext

            filters:
                tags: "@managing_catalog_promotions && @ui"
