# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

default:
    suites:
        ui_managing_catalog_promotions:
            contexts:
                - sylius.behat.context.hook.doctrine_orm

                - sylius.behat.context.transform.channel
                - sylius.behat.context.transform.lexical
                - sylius.behat.context.transform.locale
                - sylius.behat.context.transform.product
                - sylius.behat.context.transform.product_variant
                - sylius.behat.context.transform.shared_storage
                - Sylius\Behat\Context\Transform\CatalogPromotionContext
                
                - sylius.behat.context.setup.admin_security
                - sylius.behat.context.setup.channel
                - sylius.behat.context.setup.product
                - Sylius\Behat\Context\Setup\CatalogPromotionContext

                - sylius.behat.context.ui.admin.notification
                - Sylius\Behat\Context\Ui\Admin\ManagingCatalogPromotionsContext

            filters:
                tags: "@managing_catalog_promotions && @ui"
