# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_account_homepage:
    pattern: /
    defaults: { _controller: FOSUserBundle:Profile:show }

sylius_account_order_index:
    pattern: /orders
    methods: [GET]
    defaults: { _controller: SyliusWebBundle:Frontend/Account:indexOrder }

sylius_account_order_show:
    pattern: /order/{number}
    methods: [GET]
    defaults: { _controller: SyliusWebBundle:Frontend/Account:showOrder }

sylius_account_order_invoice:
    path:     /invoice/{number}
    methods:  [GET]
    defaults: { _controller: SyliusWebBundle:Frontend/Account:generateInvoice }
