sylius_user_registration:
    path: /register
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.user:createAction
        _sylius:
            form: sylius_user_registration
            event: register
            template: SyliusWebBundle:Frontend/User:register.html.twig
            redirect: sylius_homepage

sylius_user_login:
    path: /login
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.security:loginAction
        _sylius:
            form: sylius_user_login
            template: SyliusWebBundle:Frontend/User:login.html.twig
            redirect: sylius_homepage

sylius_user_login_check:
    path: /login_check
    methods: [POST]
    defaults:
        _controller: sylius.controller.security:checkAction

sylius_user_logout:
    path: /logout
    methods: [POST]
    defaults:
        _controller: sylius.controller.security:logoutAction
