# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_backend_currency_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.currency:indexAction
        _sylius:
            template: SyliusWebBundle:Backend/Currency:index.html.twig
            sortable: true
            paginate: false

sylius_backend_currency_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.currency:createAction
        _sylius:
            template: SyliusWebBundle:Backend/Currency:create.html.twig
            redirect: sylius_backend_currency_index

sylius_backend_currency_update:
    pattern: /{id}/edit
    methods: [GET, PUT]
    defaults:
        _controller: sylius.controller.currency:updateAction
        _sylius:
            template: SyliusWebBundle:Backend/Currency:update.html.twig
            redirect: sylius_backend_currency_index

sylius_backend_currency_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: sylius.controller.currency:deleteAction
        _sylius:
            template: SyliusWebBundle:Backend/Misc:delete.html.twig
            redirect: sylius_backend_currency_index
