# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_backend_order_index:
    path: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.order:indexAction
        _sylius:
            template: SyliusWebBundle:Backend/Order:index.html.twig
            method: createFilterPaginator
            arguments: [$criteria, $sorting, $deleted]
            paginate: 20

sylius_backend_order_create:
    path: /new
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.order:createAction
        _sylius:
            template: SyliusWebBundle:Backend/Order:create.html.twig
            redirect: sylius_backend_order_show

sylius_backend_order_update:
    path: /{id}/edit
    methods: [GET, PUT]
    defaults:
        _controller: sylius.controller.order:updateAction
        _sylius:
            template: SyliusWebBundle:Backend/Order:update.html.twig
            redirect: sylius_backend_order_show

sylius_backend_order_delete:
    path: /{id}
    methods: [DELETE]
    defaults:
        _controller: sylius.controller.order:deleteAction
        _sylius:
            template: SyliusWebBundle:Backend/Misc:delete.html.twig
            redirect: sylius_backend_order_index

sylius_backend_order_show:
    path: /{id}
    methods: [GET]
    defaults:
        _controller: sylius.controller.order:showAction
        _sylius:
            template: SyliusWebBundle:Backend/Order:show.html.twig
            method: findForDetailsPage
            arguments: [$id]

sylius_backend_order_by_user:
    path: /u/{id}
    methods: [GET]
    defaults:
        _controller: sylius.controller.order:indexByUserAction
        _sylius:
            template: SyliusWebBundle:Backend/Order:indexByUser.html.twig
            sortable: true
            sorting: { updatedAt: desc }

sylius_backend_order_release_inventory:
    path: /release-inventory/{id}
    methods: [PUT]
    defaults:
        _controller: sylius.controller.order:releaseInventoryAction

sylius_backend_order_comment_create:
    path: /{id}/comment/new
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.comment:createAction
        _sylius:
            template: SyliusWebBundle:Backend/Order:createComment.html.twig

