# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

default:
    suites:
        api_customer_account:
            contexts:
                - sylius.behat.context.hook.doctrine_orm

                - sylius.behat.context.transform.country
                - sylius.behat.context.transform.customer
                - sylius.behat.context.transform.user

                - sylius.behat.context.setup.channel
                - sylius.behat.context.setup.currency
                - sylius.behat.context.setup.customer
                - sylius.behat.context.setup.shop_api_security
                - sylius.behat.context.setup.user
                    
                - sylius.behat.context.api.shop.account

            filters:
                tags: "@customer_account && @api"
