# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_user_request_verification_token:
    path: /
    methods: [POST]
    defaults:
        _controller: sylius.controller.user:requestVerificationTokenAction

sylius_user_verification:
    path: /{email}/{token}
    methods: [GET]
    defaults:
        _controller: sylius.controller.user:verifyAction
