# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_addressing_backend_address_create:
    pattern: /create
    defaults: { _controller: sylius_addressing.controller.backend.address:createAction }

sylius_addressing_backend_address_update:
    pattern: /{id}/update
    defaults: { _controller: sylius_addressing.controller.backend.address:updateAction }

sylius_addressing_backend_address_delete:
    pattern: /{id}/delete
    defaults: { _controller: sylius_addressing.controller.backend.address:deleteAction }

sylius_addressing_backend_address_list:
    pattern: /list
    defaults: { _controller: sylius_addressing.controller.backend.address:listAction }

sylius_addressing_backend_address_show:
    pattern: /{id}
    defaults: { _controller: sylius_addressing.controller.backend.address:showAction }
