name: Documentation

on:
    push:
        branches-ignore:
            - 'dependabot/**'
        paths:
            - "docs/**"
    pull_request:
        paths:
            - "docs/**"
    release:
        types: [created]
    schedule:
        -
            cron: "0 1 * * 6" # Run at 1am every Saturday
    workflow_dispatch: ~

jobs:
    test:
        runs-on: ubuntu-18.04
        
        name: "Build"

        timeout-minutes: 10
        
        steps:
            -
                uses: actions/checkout@v2

            -
                name: Install documentation dependencies
                run: docker build -t sylius-docs docs

            -
                name: Build the documentation
                run: docker run --rm sylius-docs

    notify-about-build-failure:
        runs-on: ubuntu-18.04

        if: failure() && (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'release' || github.event_name == 'workflow_dispatch')

        needs: [test]

        name: "Notify about build failure"

        timeout-minutes: 5

        steps:
            -   
                name: "Notify on Slack"
                uses: SyliusLabs/SlackBuildNotificationAction@main
                env:
                    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
