name: Upmerge PR

on:
    schedule:
        -
            cron: "0 2 * * *"
    workflow_dispatch: ~

jobs:
    upmerge:
        runs-on: ubuntu-latest
        if: github.repository == 'Sylius/Sylius'
        name: "Upmerge PR"
        timeout-minutes: 5
        strategy:
            fail-fast: false
            matrix:
                include:
                    -
                        base_branch: "1.12"
                        target_branch: "1.13"

        steps:
            -
                uses: actions/checkout@v3
                with:
                    ref: ${{ matrix.base_branch }}

            -
                name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.0

            -
                name: Create Pull Request
                uses: peter-evans/create-pull-request@v4
                with:
                    token: ${{ secrets.SYLIUS_BOT_PAT }}
                    title: '[UPMERGE] ${{ matrix.base_branch }} -> ${{ matrix.target_branch }}'
                    body: |
                        This PR has been generated automatically.
                        For more details see [refactor.yaml](/Sylius/Sylius/blob/1.13/.github/workflows/upmerge_pr.yaml).
                        
                        **Remember!** Use **rebase strategy** when merging this PR.
                    branch: "upmerge/${{ matrix.base_branch }}_${{ matrix.target_branch }}"
                    delete-branch: true
                    branch-suffix: "short-commit-hash"
                    base: ${{ matrix.target_branch }}
